/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // homepage: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // myAutogeneratedSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.', // '.' means the current docs folder
  //   },
  // ],

  homepage: [
    // {
    //   type: "doc",
    //   id: "homepage",
    //   label: "Overview",
    //   className: "homepage-sidebar-item",
    //   customProps: {
    //     sidebar_icon: "BiHomeAlt",
    //   },
    // },
    {
      type: "category",
      label: "Getting Started",
      className: "homepage-sidebar-item",
      link: {
        type: "doc",
        id: "getting-started",
      },
      customProps: {
        sidebar_icon: "BiRocket",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "getting-started/cli-install",
          label: "CLI Installation",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/platform-installation",
          label: "Platform Installation",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/first-capsule",
          label: "Your first Capsule",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/next-steps",
          label: "Next Steps",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "Platform",
      className: "homepage-sidebar-divider",
    },
    {
      type: "category",
      label: "Capsules",
      link: { type: "doc", id: "capsules" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCapsule",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "capsules/create-deploy",
          label: "Deploy your Application",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "capsules/manage-capsules",
          label: "Manage Capsules",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "capsules/github-actions",
          label: "Github Actions",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "doc",
      id: "platform/builds",
      label: "Builds",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "doc",
      id: "platform/rollouts",
      label: "Rollouts",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "doc",
      id: "platform/docker-registries",
      label: "Docker Registries",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "doc",
      id: "platform/config-files",
      label: "Config Files",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "doc",
      id: "platform/container-settings",
      label: "Container Settings",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "doc",
      id: "platform/network-interfaces",
      label: "Network Interfaces",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "category",
      label: "CI/CD",
      link: { type: "doc", id: "platform/ci-cd" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCapsule",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "platform/ci-cd/github-actions",
          label: "GitHub Actions",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "platform/ci-cd/circle-ci",
          label: "CircleCI [Preview]",
          className: "docpage-sidebar-item",
        },
      ],
    },

    {
      type: "html",
      value: "Operator Manual",
      className: "homepage-sidebar-divider",
    },
    {
      type: "category",
      label: "Setup guide",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      // collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [],
    },
    {
      type: "category",
      label: "Architecture",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      // collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [],
    },
    {
      type: "category",
      label: "GitOps",
      link: { type: "doc", id: "capsules" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCapsule",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "capsules/create-deploy",
          label: "Setup with Flux",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "capsules/manage-capsules",
          label: "Setup with Argo CD",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "category",
      label: "Ingress",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      // collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [],
    },
    {
      type: "category",
      label: "Secrets",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      // collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [],
    },
    {
      type: "category",
      label: "CRD & Operator",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      // collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [
        {
          type: "doc",
          id: "capsules/create-deploy",
          label: "Capsule Spec",
          className: "docpage-sidebar-item",
        },
      ],
    },



    {
      type: "html",
      value: "Dev Tools",
      className: "homepage-sidebar-divider",
    },
    {
      type: "doc",
      id: "dev-tools/cli",
      label: "CLI",
      className: "homepage-sidebar-item",
    },

    {
      type: "html",
      value: "Additional Resources",
      className: "homepage-sidebar-divider",
    },

    {
      type: "doc",
      id: "usage",
      label: "Usage",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },


  ],
};

module.exports = sidebars;
