/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // homepage: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // myAutogeneratedSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.', // '.' means the current docs folder
  //   },
  // ],

  homepage: [
    // {
    //   type: "doc",
    //   id: "homepage",
    //   label: "Overview",
    //   className: "homepage-sidebar-item",
    //   customProps: {
    //     sidebar_icon: "BiHomeAlt",
    //   },
    // },
    {
      type: "category",
      label: "Getting Started",
      className: "homepage-sidebar-item",
      link: {
        type: "doc",
        id: "getting-started",
      },
      customProps: {
        sidebar_icon: "BiRocket",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "getting-started/server-installation",
          label: "Server Installation",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/cli-setup",
          label: "CLI Setup",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/first-capsule",
          label: "Your first Capsule",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "getting-started/next-steps",
          label: "Next Steps",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "Platform",
      className: "homepage-sidebar-divider",
    },
    {
      type: "category",
      label: "Capsules",
      link: { type: "doc", id: "capsules" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCapsule",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "capsules/create-deploy",
          label: "Deploy your Application",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "capsules/manage-capsules",
          label: "Manage Capsules",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "capsules/github-actions",
          label: "Github Actions",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "doc",
      id: "service-accounts",
      label: "Service Accounts",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiKey",
      },
    },
    {
      type: "html",
      value: "Modules",
      className: "homepage-sidebar-divider",
    },

    {
      type: "category",
      label: "Users",
      link: { type: "doc", id: "users" },
      collapsed: true,
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiUser",
      },
      items: [
        {
          type: "doc",
          id: "users/create-users",
          label: "Creating Users",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/manage-users",
          label: "Managing Users",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/delete-users",
          label: "Deleting Users",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/create-groups",
          label: "Creating Groups",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/manage-groups",
          label: "Managing Groups",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/manage-members",
          label: "Managing Members",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "users/delete-groups",
          label: "Deleting Groups",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      className: "homepage-sidebar-item",
      link: { type: "doc", id: "auth" },
      collapsed: true,
      customProps: {
        sidebar_icon: "BiLock",
      },
      items: [
        {
          type: "doc",
          id: "auth/register",
          label: "Registering Users",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/login",
          label: "User Login",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/social-login",
          label: "Social Login",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/reset-password",
          label: "Resetting Passwords",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/logout",
          label: "User Logout",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/auth-settings",
          label: "Auth Settings",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/auth-templates",
          label: "Templates",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "auth/advanced",
          label: "Advanced",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "category",
      label: "Database",
      link: { type: "doc", id: "database" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiData",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "database/connect-mongo",
          label: "Connecting to MongoDB",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "database/create-database",
          label: "Creating Databases",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "database/manage-database",
          label: "Managing Databases",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "database/delete-database",
          label: "Deleting Databases",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "database/create-credential",
          label: "Creating Credentials",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "database/delete-credential",
          label: "Deleting Credentials",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "category",
      label: "Storage",
      link: { type: "doc", id: "storage" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiFolder",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "storage/providers",
          label: "Providers",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/buckets",
          label: "Buckets",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/manage-objects",
          label: "Managing Objects",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/uploading-objects",
          label: "Uploading Objects",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/downloading-objects",
          label: "Downloading Objects",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/gcs",
          label: "Setup Google Cloud Storage",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/minio",
          label: "Setup Minio Storage",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "storage/s3",
          label: "Setup Amazon S3 Storage",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "Self-Hosting",

      className: "homepage-sidebar-divider",
    },
    {
      type: "doc",
      id: "configuration",
      label: "Configuration",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCog",
      },
    },
    {
      type: "doc",
      id: "kubernetes",
      label: "Kubernetes",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "kubernetes",
      },
    },
    {
      type: "category",
      label: "Cluster Management",
      link: { type: "doc", id: "cluster" },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiBuilding",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "cluster/access-admin-cli",
          label: "Use the Admin CLI",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "cluster/manage-admin-users",
          label: "Manage Admin Users",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "Dev Tools",
      className: "homepage-sidebar-divider",
    },
    {
      type: "category",
      label: "SDKs",
      link: {
        type: "doc",
        id: "sdks",
      },
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiCode",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "sdks/golang",
          label: "Golang",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "sdks/typescript",
          label: "Typescript",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "html",
      value: "Additional Resources",
      className: "homepage-sidebar-divider",
    },
    {
      type: "category",
      label: "Examples",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiHardHat",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "examples/todo",
          label: "TODO-List Web App",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "examples/oauth",
          label: "User Management - OAuth",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "examples/database",
          label: "Database",
          className: "docpage-sidebar-item",
        },
      ],
    },
    {
      type: "category",
      label: "Migration",
      className: "homepage-sidebar-item",
      customProps: {
        sidebar_icon: "BiImport",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "migration/custom",
          label: "Custom",
          className: "docpage-sidebar-item",
        },
        {
          type: "doc",
          id: "migration/firebase",
          label: "Firebase",
          className: "docpage-sidebar-item",
        },
      ],
    },
  ],
};

module.exports = sidebars;
